### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by Vishnu-M-E** [Vishnu-M-E/Hacktoberfest-2024#1]
Find what's wrong with the code in Day1/issue1.c.
(Hint: Something wrong with the logic maybe?)

**Comment by sumanth-0** [comment]
It looks like you're trying to compute the sum of even and odd numbers, but there are a few issues with the logic that need correcting. The dictionary comprehensions you have created are adding 2 to each key in the range, but the sums you're trying to compute seem to aim at adding the actual values from the sequences of even and odd numbers. Assign me this issue and i will write the corrected code

**Comment by swayam-agrahari** [comment]
You don't have to wait to be assigned. You can start working and make a pr. Upon reviewing your code, we will merge it : )

**Comment by Jelina-bhatt** [comment]
The code has the following issues:

Space printing loop: The condition uses j--, causing an infinite loop. It should increment (j++) to print spaces correctly.

Missing star print: In the star-printing loop, printf(""); is empty, so no stars are printed. It should be printf("*").

Unnecessary extra star and tab: printf("*"); and printf("\t"); are misplaced and result in incorrect formatting. These should be removed.

Redundant printf("%d \n", rows);: This line prints the number of rows unnecessarily unless intended for debugging or additional output.

@Vishnu-M-E hello vishnu iam ready to take this issue 
so assign me this issue .
